### ISSUE TITLE
fix: /hero links

### ISSUE THREAD

**Issue by kymppi** [HackSquadDev/discord-rust#17]
1. The "Hero Page" button links to github and not to https://novu.co/contributors/...
1. Links in "Last 3 PRs" go to api.github.com and not the pull request

**Comment by diwash007** [comment]
Alright, I ll Give it a go

**Comment by washbin** [comment]
okay assigning it to you! have fun rusting around :smirk:

**Comment by kymppi** [comment]
Nice, you can create a hotfix branch with git flow.

**Comment by washbin** [comment]
> Nice, you can create a hotfix branch with git flow.

cool, how does hotfix's changes get to main and next though ?
Is there a automated setup for that or do we have to manually do it ?

**Comment by kymppi** [comment]
> > Nice, you can create a hotfix branch with git flow.
> 
> cool, how does hotfix's changes get to main and next though ? Is there a automated setup for that or do we have to manually do it ?

You need to make a PR to the branch `next`. main is the currently released branch. We will probably make a new release shortly

**Comment by kymppi** [comment]
Fixed in #18
